databaseUrl=mongodb://mongodb:27017
databaseName=ead_ca2
databaseCollection=ead_2024

# Enable the env endpoint
management.endpoints.web.exposure.include=env

org.springframework.web.servlet.mvc.method.annotation=DEBUG
logging.logger.org.springframework.web.servlet.mvc.method.annotation=DEBUG, console
logging.level.org.springframework.web=DEBUG
spring.http.log-request-details=true
